---
- name: Determine Homebrew ownership variables
  set_fact:
    homebrew_user: '{{ homebrew_user | default(ansible_user_id) }}'
    homebrew_group: '{{ homebrew_group | default(ansible_user_gid) }}'

# Homebrew setup prerequisites.
- name: Ensure Homebrew parent directory has correct permissions (M1).
  file:
    path: "{{ homebrew_prefix }}"
    owner: "{{ homebrew_user }}"
    state: directory
  when: ansible_machine == 'arm64'

- name: Ensure Homebrew parent directory has correct permissions (Intel).
  block:
    - name: Ensure Homebrew parent directory has correct permissions (MacOS >= 10.13).
      file:
        path: "{{ homebrew_prefix }}"
        owner: root
        state: directory
      when: "ansible_distribution_version is version('10.13', '>=')"

- name: Ensure Homebrew directory exists.
  file:
    path: "{{ homebrew_install_path }}"
    owner: "{{ homebrew_user }}"
    group: "{{ homebrew_group }}"
    state: directory
    mode: 0775

# Clone Homebrew.
- name: Ensure Homebrew is installed.
  git:
    repo: "{{ homebrew_repo }}"
    version: master
    dest: "{{ homebrew_install_path }}"
    update: false
    depth: 1
  become: true
  become_user: "{{ homebrew_user }}"

# Adjust Homebrew permissions.
- name: Ensure proper permissions and ownership on homebrew_bin_path dirs.
  file:
    path: "{{ homebrew_bin_path }}"
    state: directory
    owner: "{{ homebrew_user }}"
    group: "{{ homebrew_group }}"
    mode: 0775

- name: Ensure proper ownership on homebrew_install_path subdirs.
  file:
    path: "{{ homebrew_install_path }}"
    state: directory
    owner: "{{ homebrew_user }}"
    group: "{{ homebrew_group }}"
    recurse: true

# Place brew binary in proper location and complete setup.
- name: Check if homebrew binary is already in place.
  stat: "path={{ homebrew_bin_path }}/brew"
  register: homebrew_binary
  check_mode: false

- name: Symlink brew to homebrew_bin_path.
  file:
    src: "{{ homebrew_install_path }}/bin/brew"
    dest: "{{ homebrew_bin_path }}/brew"
    state: link
  when: not homebrew_binary.stat.exists

- name: Ensure proper homebrew folders are in place.
  file:
    path: "{{ homebrew_prefix }}/{{ item }}"
    state: directory
    owner: "{{ homebrew_user }}"
    group: "{{ homebrew_group }}"
  loop: "{{ homebrew_folders_base }}"
  
- block:
  - name: Force update brew after installation.
    command: "{{ homebrew_bin_path }}/brew update --force"
    when: not homebrew_binary.stat.exists

  - name: Where is the cache?
    command: "{{ homebrew_bin_path }}/brew --cache"
    register: homebrew_cache_path
    changed_when: false
    check_mode: false

  # Taps
  - name: Ensure configured taps are tapped.
    homebrew_tap:
      tap: '{{ item.name | default(item) }}'
      url: '{{ item.url | default(omit) }}'
      state: present
    loop: "{{ homebrew_taps }}"

  # Brewfile
  - name: Check for Brewfile.
    stat:
      path: "{{ homebrew_brewfile_dir }}/Brewfile"
    register: homebrew_brewfile
    check_mode: false

  - name: Install from Brewfile.
    command: "{{ homebrew_bin_path }}/brew bundle chdir={{ homebrew_brewfile_dir }}"
    when: homebrew_brewfile.stat.exists and homebrew_use_brewfile

  # Privilege escalation is only required for inner steps when
  # the `homebrew_user` doesn't match the `ansible_user_id`
  become: "{{ (homebrew_user != ansible_user_id) | bool }}"
  become_user: "{{ homebrew_user }}"